### ISSUE TITLE
Cannot open Queue.h

### ISSUE THREAD

**Issue by sboettger** [kitecraft/Multiple_TFT_Displays#1]
https://github.com/kitecraft/Multiple_TFT_Displays/blob/4517ffa38672c560cd6248595e45483cf2a06746/Triple_TFT/src/DisplayHandler/DisplayHandler.h#L7

Hi kitecraft

thank you very much for this library. Unfortunately my vscode cannot find the Queue.h. Even if I insert Queue@1.8 as lib dev. Could you please tell me which one you are using?

Thank you
Sebastian

**Comment by kitecraft** [comment]
Hi.  Thanks for letting me know.  I forgot that was in the code still.   That was bad of me.
Anyways, the proper lib is actually called 'ArduinoQueue' by Einar Arnason .  It can be found in the Arduino library manager, or here:  https://github.com/EinarArnason/ArduinoQueue

**Comment by sboettger** [comment]
Thanks 🙂👍

**Comment by kitecraft** [comment]
I just noticed that he actually updated the ArduinoQueue library and changed the names.  I've fixed my Triple_TFT example to work with it now.  Pull the latest version for fixes.  Thanks buddy.
