### ISSUE TITLE
Queues options

### ISSUE THREAD

**Issue by poky** [kitecraft/Multiple_TFT_Displays#2]
Hi, thank you for this great example of how to use multiple displays!
I'm using to use it in my application, however the sample CS low/high just won't cut it, have to look into the queue solutions.
I've noticed that in your triple display is using AndroidQueue, since ESP also provides the FreeRTOS queues function.
Wondering what will be the better option? Thanks!

**Comment by kitecraft** [comment]
Thanks for the comment.  As for which Queue to use, I'm sorry but I have no advice there.  Haven't used the FreeRTOS queue myself.
