### ISSUE TITLE
using  1.14inch ips with st7789v

### ISSUE THREAD

**Issue by HorwinHe** [kitecraft/Multiple_TFT_Displays#3]
hi, bro, I was watched your video . I try to using TFT_eSPI driver with 1.14inch ips screen. I change the user_setup code and type the code like your video show. but it not work with two 1.14inch ips screens. it only show the color and text with one screen. the second is not display anything. did you tested the st7789 for yourself ? if you know how to do ,please tell me the way to use it. thanks for all.

**Comment by kitecraft** [comment]
If its SPI, it should work the same way.  Be sure to initialize all displays at the same time.
